version: "3.0"
services:

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    devices:
      - nvidia.com/gpu=all
    networks:
      - default
    security-opt:
      - label=disable
    volumes:
      - ollama:/root/.ollama:z
    expose:
      - 11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
    networks:
      - default
    security-opt:
      - label=disable
    volumes:
      - open-webui:/app/backend/data:z
    ports:
      - 8080:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    
volumes:
  ollama: {}
  open-webui: {}

networks:
  default:
    driver: bridge
